### ISSUE TITLE
The Turbo Logo 

### ISSUE THREAD

**Issue by Demonstrandum** [hotwired/turbo-site#10]
This may seem very nitpicky, but isn't the fan inside the turbo logo the wrong way around, i.e. it should be mirrored.

https://github.com/hotwired/turbo-site/blob/main/images/logo.svg
![turbo-logo](https://raw.githubusercontent.com/hotwired/turbo-site/2f5beee7f404bf045002c547a7b80ce057d63098/images/logo.svg)

The fan orientation would not be ideal as gas flows from the opening to the exit.
Either the fan should be mirrored vertically or horizontally, or the chamber _with_ opening and exit should be mirrored vertically or horizontally.

Example
![example](https://www.mpoweruk.com/images/Turbine_Nozzle.gif)

**Comment by vampeel** [comment]
Thanks @Demonstrandum. Fixed in https://github.com/hotwired/turbo-site/commit/411dee6b7633d7282dc1634375d4dc687b3275f2.

**Comment by askkaz** [comment]
amazing
