### ISSUE TITLE
Document the expected HTTP status codes

### ISSUE THREAD

**Issue by kuba-orlik** [hotwired/turbo-site#111]
Turbo expects the server to respond with a 303 status code on successful form submission, but it's not mentioned anywhere in the Turbo Reference or Handbook (https://turbo.hotwired.dev/reference/drive). Same goes for the 422 status code when you want to render a form error state.

I've invited some people to use Turbo and the status code nuances really negatively impacted their learning curve (they did not use Turbo in conjunction with Rails)

**Comment by seanpdoyle** [comment]
Thank you for opening this issue @kuba-orlik!

The "Redirecting After a Form Submission" section of the [Turbo Handbook](https://turbo.hotwired.dev/handbook/drive#redirecting-after-a-form-submission) mentions both the [303 See other](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/303) and [422 Unprocessible entity](https://developer.mozilla.org/ru/docs/Web/HTTP/Status/422) status codes.

What kinds of improvements to that section or the Reference would make that information more discoverable?

**Comment by kuba-orlik** [comment]
Ah, sorry about that. I manually did ctrl+f for "422" on most of the subpages and must've missed https://turbo.hotwired.dev/handbook/drive. My bad.
