### ISSUE TITLE
Turbo build error

### ISSUE THREAD

**Issue by avarik-anam** [hotwired/turbo-site#112]
/*
 * [Package Error] "@hotwired/turbo@v7.2.0" could not be built. 
 *
 * No build output found.
 *
 * How to fix:
 *   - If you believe this to be an error in Skypack, file an issue here: https://github.com/skypackjs/skypack-cdn/issues
 *   - If you believe this to be an issue in the package, share this URL with the package authors to help them debug & fix.
 *   - Use https://skypack.dev/ to find a web-friendly alternative to find another package.
 */

console.warn("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
throw new Error("[Package Error] \"@hotwired/turbo@v7.2.0\" could not be built. ");
export default null;

**Comment by marcoroth** [comment]
Hey @3ch3r46, sadly this is an issue on Skypack's part. 

See https://github.com/hotwired/turbo/issues/731 and https://github.com/skypackjs/skypack-cdn/issues/319 for context.

**Comment by marcoroth** [comment]
Hey @avarik-anam, were you able to resolve this? The latest version on skypack seems to be working fine again!
