### ISSUE TITLE
Missing Documentation for Turbo.setFormMode

### ISSUE THREAD

**Issue by nzifnab** [hotwired/turbo-site#189]
While looking for a way to disable turbo for form submissions (due to compatibility issues while trying to add turbo to a mature rails site), I ran across this: https://stackoverflow.com/questions/70921317/how-can-i-disable-hotwire-turbo-the-turbolinks-replacement-for-all-forms-in

which links to this merged-in feature: https://github.com/hotwired/turbo/pull/419

But `Turbo.setFormMode` appears to be undocumented on the turbo documentation site, making it's discoverability difficult, and making it unclear whether that's an intended feature or a hidden implementation detail that may change in the future.

Can we get this documented?

**Comment by brunoprietog** [comment]
Hi @nzifnab, feel free to open a PR and we can merge it!
