### ISSUE TITLE
Missing distributable script? (from installation docs)

### ISSUE THREAD

**Issue by davidbgk** [hotwired/turbo-site#21]
> You can download the latest distributable script from the GitHub releases page, then reference that in your <script> tag on your page. — https://turbo.hotwire.dev/handbook/installing (§ In Compiled Form)

I think that script is missing from the build in the released archive from the source code download at https://github.com/hotwired/turbo/releases/tag/v7.0.0-beta.1

It would be handy and more accessible to make it available without installing all the tooling (or to change the doc accordingly).

Or maybe at least provide a link to https://unpkg.com/browse/@hotwired/turbo@7.0.0-beta.1/dist/ if that is the “[official](https://github.com/hotwired/turbo/issues/18#issuecomment-749722776)” way.

(See [previous issue on the turbo repo](https://github.com/hotwired/turbo/issues/43) and [answer from @sstephenson](https://github.com/hotwired/turbo/issues/43#issuecomment-754221587))

**Comment by davidbgk** [comment]
I guess the [line here](https://github.com/hotwired/turbo-site/blob/main/docs/handbook/07_installing.md#in-compiled-form) must be rephrased to link to unpkg and not mention anymore the released version on Github for such inclusion.

**Comment by cbrandtbuffalo** [comment]
I also ran into this after reading the docs and looking through all of the files in the tarball. Maybe if someone could confirm the correct guidance, a PR could be submitted?

**Comment by wyaeld** [comment]
The instructions are still incorrect, there is no distributable.

**Comment by fritzmg** [comment]
> Or maybe at least provide a link to https://unpkg.com/browse/@hotwired/turbo@7.0.0-beta.1/dist/ if that is the “[official](https://github.com/hotwired/turbo/issues/18#issuecomment-749722776)” way.

Or rather https://unpkg.com/browse/@hotwired/turbo@latest/dist/

**Comment by dhh** [comment]
Updated instructions for now: https://github.com/hotwired/turbo-site/commit/c7e88882cfabc71605a18b5de0a7796c5b12571b

**Comment by dhh** [comment]
If anyone wants to look at getting the compiled packages going again, please do.
