### ISSUE TITLE
Hotwire website renders with unreadable font in Firefox

### ISSUE THREAD

**Issue by xhafan** [hotwired/turbo-site#27]
Firefox version 84.0.2

https://turbo.hotwire.dev/: 
![image](https://user-images.githubusercontent.com/13038902/103951908-c5e76d80-513f-11eb-8572-52249a417d99.png)

Chrome and Edge are fine.

Cheers for fixing!

**Comment by dhh** [comment]
Can't replicate. Same version on Mac:

<img width="865" alt="image" src="https://user-images.githubusercontent.com/2741/103998597-72efd380-519c-11eb-826a-6e054e734deb.png">

**Comment by xhafan** [comment]
On another PC the same. Both PCs Windows 7 SP1, Firefox 76.0.1 on one PC, 84.0.2 on another PC. It initially renders ok for like half a second, and then the font turns unreadable.

**Comment by dhh** [comment]
Ah, I was testing on Mac. Maybe it's a Mac font issue. Looping in Adam.

**Comment by xhafan** [comment]
Example video: https://www.youtube.com/watch?v=47tYW5EFkWw

**Comment by vampeel** [comment]
Things are working fine on FF84.02 for me on Windows 10:
![Screenshot 2021-01-08 11 49 58](https://user-images.githubusercontent.com/1004539/104058165-27432700-51a8-11eb-839d-d0c79913c774.png)

Looks like this is a known Windows 7 bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1508214

@xhafan do you see similar issues on the sites reported in the bug, like v-fonts.com?

**Comment by xhafan** [comment]
v-fonts.com does not work in Firefox on Windows 7. Does that mean I need to use Chrome on Windows 7 to use hotwired website?

**Comment by dhh** [comment]
Yes. [Windows 7 is EOL in 4 days](https://www.microsoft.com/en-us/windows/windows-7-end-of-life-support-information). This is not something we'll spend time investigating a fix to.

**Comment by xhafan** [comment]
No worries, thanks for looking into this, I thought there is a bug.
