### ISSUE TITLE
Could we translate your documents EN -> JA?

### ISSUE THREAD

**Issue by yakitorii** [hotwired/turbo-site#96]
We would like to translate your Turbo handbook (EN->JA) for introducing Hotwire to Japanese rails community.
We are [Everyleaf Coporation](https://everyleaf.com/english) in Japan.
Our company has 15 years history, and from the first of it we are experts of Ruby and Ruby on Rails.
There are two ways to do that. Translating them in new repository under [our company's GH organization](https://github.com/everyleaf)' or in this repository.
Which is better for you?
We think our repository is better because currently your repository looks not ready for i18n.
Of course we will specify the origin on our page, and report to you when we publish it each time.

Thank you.

**Comment by dhh** [comment]
You can translate them under your own organization, just make sure to clearly spell out that this is a translation maintained on your end, and point to the original. Thanks!

**Comment by yakitorii** [comment]
I got them, Thank you!

**Comment by yakitorii** [comment]
@dhh  It took quite a while, but we've finally launched the Japanese translation site for the handbook!
You can check it out here: https://everyleaf.github.io/hotwire_ja/

We'll continue to expand our other references as well. Thank you!

**Comment by dhh** [comment]
Awesome ✌️
